version: '3'
services:
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: animals
      MYSQL_PASSWORD: secret 
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
       - dbdata:/var/lib/mysql
volumes:
  dbdata:
    driver: local


  